### ISSUE TITLE
Problems with building the plugin

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#11]
When I fork/clone the repo and want to build the plugin on my local machine I have  following problem

- `.lock` file- due to changes in Obsidian API version  it throws me  errors, I  fixed it by just deleting it
-  whem I run `npm run dev` I gett error about no '.svelte-kit/tsconfig.json'to this repo
```
> rollup --config rollup.config.js -w
rollup v3.28.1
bundles src/main.ts → dist...
(!) Plugin typescript: @rollup/plugin-typescript TS5083: Cannot read file '/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/.svelte-kit/tsconfig.json'.
[!] (plugin typescript) RollupError: @rollup/plugin-typescript: Couldn't process compiler options
    at error (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Object.error (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1720:20)
    at emitParsedOptionsErrors (file:///Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/@rollup/plugin-typescript/dist/es/index.js:355:17)
    at Object.buildStart (file:///Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/@rollup/plugin-typescript/dist/es/index.js:759:13)
    at /Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1913:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async PluginDriver.hookParallel (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1841:9)
    at async /Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:27059:13
    at async catchUnfinishedHookActions (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:26317:16)
```
I tried to add a default svelte config but it doesn't work 
```
(!) Plugin typescript: @rollup/plugin-typescript TS18003: No inputs were found in config file '/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/tsconfig.json'. Specified 'include' paths were '[".svelte-kit/src/**/*.ts",".svelte-kit/src/**/*.svelte"]' and 'exclude' paths were '[]'.
[!] (plugin typescript) RollupError: @rollup/plugin-typescript: Couldn't process compiler options
    at error (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Object.error (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1720:20)
    at emitParsedOptionsErrors (file:///Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/@rollup/plugin-typescript/dist/es/index.js:355:17)
    at Object.buildStart (file:///Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/@rollup/plugin-typescript/dist/es/index.js:759:13)
    at /Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1913:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async PluginDriver.hookParallel (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:1841:9)
    at async /Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:27059:13
    at async catchUnfinishedHookActions (/Users/daniel/PhD/thesis-vault/projects/obsidian-writing-goals/node_modules/rollup/dist/shared/rollup.js:26317:16)
```

**Comment by lynchjames** [comment]
Did you run `npm install`? .svelte-kit is ignored from git as it should be created from the package install I think.

**Comment by lynchjames** [comment]
I've removed the dependency on the local .svelte-kit folder so `npm run dev` should run. 

The plugin will be installed into the `test-vault` folder which you can open in Obsidian to run and debug the plugin locally.

**Comment by lynchjames** [comment]
There are no release versions for the API to pin at. I've changed this to latest instead of the url.

**Comment by danieltomasz** [comment]
your  lock file has 
```
"node_modules/obsidian": {
			"version": "1.4.0",
...
```

even after your latest commit I was forced to recreate `package-lock.json` 

latest is ok, but some packages refer to minimal version, obsidian-zotero-integration has it pinned to 1.2.8
https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/package.json#:~:text=%7B%0A%20%20%22name%22%3A%20%22obsidian-sample,68

**Comment by lynchjames** [comment]
Ah, they have versions in npm but not GH. The Obsidian API provides TS types for using the API. I would prefer to follow latest by default and pin to a version if there is an incompatibility to be fixed.

I ran `npm update` and now package-lock has Obsidian as "latest".
